name: BiomeCompass
version: ${project.version}
main: com.sigong.BiomeCompass.BiomeCompass
api-version: 1.13
commands:
  createcompass:
    description: 'Creates a biome compass. You may optionally specify a player to receive the compass.'
    usage: "/<command> <biome> [player]"
  biomecompass:
    description: "Main plugin command. Currently only used to reload the plugin's copy of config files."
    usage: "/<command> reload"